# BLE Sync Cycle TOML configuration
# 0.5.0

[ble]
  sensor_uuid = "F1:42:D8:DE:35:16" # UUID of BLE peripheral device
  scan_timeout_secs = 30            # Seconds to wait for peripheral response before generating error

[speed]
  smoothing_window = 5          # Number of speed look-backs to use for generating a moving average
  speed_threshold = 1.0         # Minimum speed change to trigger video speed update
  wheel_circumference_mm = 1932 # Wheel circumference in millimeters
  speed_units = "mph"           # "km/h" or "mph"

[video]
  file_path = "cycling_test.webm" # Path to the video file to play
  update_interval_sec = 1        # Seconds to wait between video player updates
  speed_multiplier = 0.6         # Multiplier that translates sensor speed (km/h or mph) to
                                 # video playback speed (0.0 = stopped, 1.0 = normal speed)
